//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace WSTEST1.ServiceReference1 {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ServiceReference1.WebServiceTestSoap")]
    public interface WebServiceTestSoap {
        
        // CODEGEN: 命名空间 http://tempuri.org/ 的元素名称 HelloWorldResult 以后生成的消息协定未标记为 nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/HelloWorld", ReplyAction="*")]
        WSTEST1.ServiceReference1.HelloWorldResponse HelloWorld(WSTEST1.ServiceReference1.HelloWorldRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/HelloWorld", ReplyAction="*")]
        System.Threading.Tasks.Task<WSTEST1.ServiceReference1.HelloWorldResponse> HelloWorldAsync(WSTEST1.ServiceReference1.HelloWorldRequest request);
        
        // CODEGEN: 命名空间 http://tempuri.org/ 的元素名称 str 以后生成的消息协定未标记为 nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Sort", ReplyAction="*")]
        WSTEST1.ServiceReference1.SortResponse Sort(WSTEST1.ServiceReference1.SortRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Sort", ReplyAction="*")]
        System.Threading.Tasks.Task<WSTEST1.ServiceReference1.SortResponse> SortAsync(WSTEST1.ServiceReference1.SortRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class HelloWorldRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="HelloWorld", Namespace="http://tempuri.org/", Order=0)]
        public WSTEST1.ServiceReference1.HelloWorldRequestBody Body;
        
        public HelloWorldRequest() {
        }
        
        public HelloWorldRequest(WSTEST1.ServiceReference1.HelloWorldRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class HelloWorldRequestBody {
        
        public HelloWorldRequestBody() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class HelloWorldResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="HelloWorldResponse", Namespace="http://tempuri.org/", Order=0)]
        public WSTEST1.ServiceReference1.HelloWorldResponseBody Body;
        
        public HelloWorldResponse() {
        }
        
        public HelloWorldResponse(WSTEST1.ServiceReference1.HelloWorldResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class HelloWorldResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string HelloWorldResult;
        
        public HelloWorldResponseBody() {
        }
        
        public HelloWorldResponseBody(string HelloWorldResult) {
            this.HelloWorldResult = HelloWorldResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class SortRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="Sort", Namespace="http://tempuri.org/", Order=0)]
        public WSTEST1.ServiceReference1.SortRequestBody Body;
        
        public SortRequest() {
        }
        
        public SortRequest(WSTEST1.ServiceReference1.SortRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class SortRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string str;
        
        public SortRequestBody() {
        }
        
        public SortRequestBody(string str) {
            this.str = str;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class SortResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="SortResponse", Namespace="http://tempuri.org/", Order=0)]
        public WSTEST1.ServiceReference1.SortResponseBody Body;
        
        public SortResponse() {
        }
        
        public SortResponse(WSTEST1.ServiceReference1.SortResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class SortResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string SortResult;
        
        public SortResponseBody() {
        }
        
        public SortResponseBody(string SortResult) {
            this.SortResult = SortResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface WebServiceTestSoapChannel : WSTEST1.ServiceReference1.WebServiceTestSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class WebServiceTestSoapClient : System.ServiceModel.ClientBase<WSTEST1.ServiceReference1.WebServiceTestSoap>, WSTEST1.ServiceReference1.WebServiceTestSoap {
        
        public WebServiceTestSoapClient() {
        }
        
        public WebServiceTestSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public WebServiceTestSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public WebServiceTestSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public WebServiceTestSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        WSTEST1.ServiceReference1.HelloWorldResponse WSTEST1.ServiceReference1.WebServiceTestSoap.HelloWorld(WSTEST1.ServiceReference1.HelloWorldRequest request) {
            return base.Channel.HelloWorld(request);
        }
        
        public string HelloWorld() {
            WSTEST1.ServiceReference1.HelloWorldRequest inValue = new WSTEST1.ServiceReference1.HelloWorldRequest();
            inValue.Body = new WSTEST1.ServiceReference1.HelloWorldRequestBody();
            WSTEST1.ServiceReference1.HelloWorldResponse retVal = ((WSTEST1.ServiceReference1.WebServiceTestSoap)(this)).HelloWorld(inValue);
            return retVal.Body.HelloWorldResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<WSTEST1.ServiceReference1.HelloWorldResponse> WSTEST1.ServiceReference1.WebServiceTestSoap.HelloWorldAsync(WSTEST1.ServiceReference1.HelloWorldRequest request) {
            return base.Channel.HelloWorldAsync(request);
        }
        
        public System.Threading.Tasks.Task<WSTEST1.ServiceReference1.HelloWorldResponse> HelloWorldAsync() {
            WSTEST1.ServiceReference1.HelloWorldRequest inValue = new WSTEST1.ServiceReference1.HelloWorldRequest();
            inValue.Body = new WSTEST1.ServiceReference1.HelloWorldRequestBody();
            return ((WSTEST1.ServiceReference1.WebServiceTestSoap)(this)).HelloWorldAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        WSTEST1.ServiceReference1.SortResponse WSTEST1.ServiceReference1.WebServiceTestSoap.Sort(WSTEST1.ServiceReference1.SortRequest request) {
            return base.Channel.Sort(request);
        }
        
        public string Sort(string str) {
            WSTEST1.ServiceReference1.SortRequest inValue = new WSTEST1.ServiceReference1.SortRequest();
            inValue.Body = new WSTEST1.ServiceReference1.SortRequestBody();
            inValue.Body.str = str;
            WSTEST1.ServiceReference1.SortResponse retVal = ((WSTEST1.ServiceReference1.WebServiceTestSoap)(this)).Sort(inValue);
            return retVal.Body.SortResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<WSTEST1.ServiceReference1.SortResponse> WSTEST1.ServiceReference1.WebServiceTestSoap.SortAsync(WSTEST1.ServiceReference1.SortRequest request) {
            return base.Channel.SortAsync(request);
        }
        
        public System.Threading.Tasks.Task<WSTEST1.ServiceReference1.SortResponse> SortAsync(string str) {
            WSTEST1.ServiceReference1.SortRequest inValue = new WSTEST1.ServiceReference1.SortRequest();
            inValue.Body = new WSTEST1.ServiceReference1.SortRequestBody();
            inValue.Body.str = str;
            return ((WSTEST1.ServiceReference1.WebServiceTestSoap)(this)).SortAsync(inValue);
        }
    }
}
