import store from "@/store";

export default [
    {
        path: "admins",
        name: "AdminadminsList",
        component: () => import("@/views/admins/list"),
        meta: { title: "管理员列表", authLogin: true },
    },
    {
        path: "adminsadd",
        name: "AdminadminsAdd",
        component: () => import("@/views/admins/add"),
        meta: { title: "添加管理员", authLogin: true },
    },
    {
        path: "adminsupdt",
        name: "AdminadminsUpdt",
        props: (route) => ({ id: route.query.id }),
        component: () => import("@/views/admins/updt"),
        meta: { title: "编辑管理员", authLogin: true },
    },
    {
        path: "adminsupdtself",
        name: "AdminadminsUpdtSelf",
        props: (route) => ({ id: store.state.user.session.id }),
        component: () => import("@/views/admins/updt"),
        meta: { title: "编辑管理员", authLogin: true },
    },
    {
        path: "yonghu",
        name: "AdminyonghuList",
        component: () => import("@/views/yonghu/list"),
        meta: { title: "用户列表", authLogin: true },
    },
    {
        path: "yonghuadd",
        name: "AdminyonghuAdd",
        component: () => import("@/views/yonghu/add"),
        meta: { title: "添加用户", authLogin: true },
    },
    {
        path: "yonghuupdt",
        name: "AdminyonghuUpdt",
        props: (route) => ({ id: route.query.id }),
        component: () => import("@/views/yonghu/updt"),
        meta: { title: "编辑用户", authLogin: true },
    },
    {
        path: "yonghuupdtself",
        name: "AdminyonghuUpdtSelf",
        props: (route) => ({ id: store.state.user.session.id }),
        component: () => import("@/views/yonghu/updt"),
        meta: { title: "编辑用户", authLogin: true },
    },
    {
        path: "lunbotu",
        name: "AdminlunbotuList",
        component: () => import("@/views/lunbotu/list"),
        meta: { title: "轮播图列表", authLogin: true },
    },
    {
        path: "lunbotuadd",
        name: "AdminlunbotuAdd",
        component: () => import("@/views/lunbotu/add"),
        meta: { title: "添加轮播图", authLogin: true },
    },
    {
        path: "lunbotuupdt",
        name: "AdminlunbotuUpdt",
        props: (route) => ({ id: route.query.id }),
        component: () => import("@/views/lunbotu/updt"),
        meta: { title: "编辑轮播图", authLogin: true },
    },
    {
        path: "zhaopianfenlei",
        name: "AdminzhaopianfenleiList",
        component: () => import("@/views/zhaopianfenlei/list"),
        meta: { title: "照片分类列表", authLogin: true },
    },
    {
        path: "zhaopianfenleiadd",
        name: "AdminzhaopianfenleiAdd",
        component: () => import("@/views/zhaopianfenlei/add"),
        meta: { title: "添加照片分类", authLogin: true },
    },
    {
        path: "zhaopianfenleiupdt",
        name: "AdminzhaopianfenleiUpdt",
        props: (route) => ({ id: route.query.id }),
        component: () => import("@/views/zhaopianfenlei/updt"),
        meta: { title: "编辑照片分类", authLogin: true },
    },
    {
        path: "zhaopianxinxi",
        name: "AdminzhaopianxinxiList",
        component: () => import("@/views/zhaopianxinxi/list"),
        meta: { title: "照片信息列表", authLogin: true },
    },
    {
        path: "zhaopianxinxi_faburen",
        name: "AdminzhaopianxinxiListfaburen",
        component: () => import("@/views/zhaopianxinxi/list-faburen"),
        meta: { title: "照片信息列表", authLogin: true },
    },
    {
        path: "zhaopianxinxiadd",
        name: "AdminzhaopianxinxiAdd",
        component: () => import("@/views/zhaopianxinxi/add"),
        meta: { title: "添加照片信息", authLogin: true },
    },
    {
        path: "zhaopianxinxiupdt",
        name: "AdminzhaopianxinxiUpdt",
        props: (route) => ({ id: route.query.id }),
        component: () => import("@/views/zhaopianxinxi/updt"),
        meta: { title: "编辑照片信息", authLogin: true },
    },
    {
        path: "zhaopianxinxidetail",
        props: (route) => ({ id: route.query.id }),
        name: "AdminzhaopianxinxiDetail",
        component: () => import("@/views/zhaopianxinxi/detail"),
        meta: { title: "照片信息详情", authLogin: true },
    },
    {
        path: "pinglun",
        name: "AdminpinglunList",
        component: () => import("@/views/pinglun/list"),
        meta: { title: "评论列表", authLogin: true },
    },
    {
        path: "pinglun_pinglunren",
        name: "AdminpinglunListpinglunren",
        component: () => import("@/views/pinglun/list-pinglunren"),
        meta: { title: "评论列表", authLogin: true },
    },
    {
        path: "pinglunadd",
        name: "AdminpinglunAdd",
        component: () => import("@/views/pinglun/add"),
        meta: { title: "添加评论", authLogin: true },
    },
    {
        path: "pinglunupdt",
        name: "AdminpinglunUpdt",
        props: (route) => ({ id: route.query.id }),
        component: () => import("@/views/pinglun/updt"),
        meta: { title: "编辑评论", authLogin: true },
    },
    {
        path: "shoucang",
        name: "AdminshoucangList",
        component: () => import("@/views/shoucang/list"),
        meta: { title: "收藏列表", authLogin: true },
    },
    {
        path: "shoucang_username",
        name: "AdminshoucangListusername",
        component: () => import("@/views/shoucang/list-username"),
        meta: { title: "收藏列表", authLogin: true },
    },
    {
        path: "dianzan",
        name: "AdmindianzanList",
        component: () => import("@/views/dianzan/list"),
        meta: { title: "点赞列表", authLogin: true },
    },
    {
        path: "dianzan_username",
        name: "AdmindianzanListusername",
        component: () => import("@/views/dianzan/list-username"),
        meta: { title: "点赞列表", authLogin: true },
    },
];
