//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace WSTEST1.ServiceReference2 {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ServiceReference2.WebServiceTestSoap")]
    public interface WebServiceTestSoap {
        
        // CODEGEN: 命名空间 http://tempuri.org/ 的元素名称 HelloWorldResult 以后生成的消息协定未标记为 nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/HelloWorld", ReplyAction="*")]
        WSTEST1.ServiceReference2.HelloWorldResponse HelloWorld(WSTEST1.ServiceReference2.HelloWorldRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/HelloWorld", ReplyAction="*")]
        System.Threading.Tasks.Task<WSTEST1.ServiceReference2.HelloWorldResponse> HelloWorldAsync(WSTEST1.ServiceReference2.HelloWorldRequest request);
        
        // CODEGEN: 命名空间 http://tempuri.org/ 的元素名称 str 以后生成的消息协定未标记为 nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/toBigSort", ReplyAction="*")]
        WSTEST1.ServiceReference2.toBigSortResponse toBigSort(WSTEST1.ServiceReference2.toBigSortRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/toBigSort", ReplyAction="*")]
        System.Threading.Tasks.Task<WSTEST1.ServiceReference2.toBigSortResponse> toBigSortAsync(WSTEST1.ServiceReference2.toBigSortRequest request);
        
        // CODEGEN: 命名空间 http://tempuri.org/ 的元素名称 str 以后生成的消息协定未标记为 nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/toSmallSort", ReplyAction="*")]
        WSTEST1.ServiceReference2.toSmallSortResponse toSmallSort(WSTEST1.ServiceReference2.toSmallSortRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/toSmallSort", ReplyAction="*")]
        System.Threading.Tasks.Task<WSTEST1.ServiceReference2.toSmallSortResponse> toSmallSortAsync(WSTEST1.ServiceReference2.toSmallSortRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class HelloWorldRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="HelloWorld", Namespace="http://tempuri.org/", Order=0)]
        public WSTEST1.ServiceReference2.HelloWorldRequestBody Body;
        
        public HelloWorldRequest() {
        }
        
        public HelloWorldRequest(WSTEST1.ServiceReference2.HelloWorldRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class HelloWorldRequestBody {
        
        public HelloWorldRequestBody() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class HelloWorldResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="HelloWorldResponse", Namespace="http://tempuri.org/", Order=0)]
        public WSTEST1.ServiceReference2.HelloWorldResponseBody Body;
        
        public HelloWorldResponse() {
        }
        
        public HelloWorldResponse(WSTEST1.ServiceReference2.HelloWorldResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class HelloWorldResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string HelloWorldResult;
        
        public HelloWorldResponseBody() {
        }
        
        public HelloWorldResponseBody(string HelloWorldResult) {
            this.HelloWorldResult = HelloWorldResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class toBigSortRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="toBigSort", Namespace="http://tempuri.org/", Order=0)]
        public WSTEST1.ServiceReference2.toBigSortRequestBody Body;
        
        public toBigSortRequest() {
        }
        
        public toBigSortRequest(WSTEST1.ServiceReference2.toBigSortRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class toBigSortRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string str;
        
        public toBigSortRequestBody() {
        }
        
        public toBigSortRequestBody(string str) {
            this.str = str;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class toBigSortResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="toBigSortResponse", Namespace="http://tempuri.org/", Order=0)]
        public WSTEST1.ServiceReference2.toBigSortResponseBody Body;
        
        public toBigSortResponse() {
        }
        
        public toBigSortResponse(WSTEST1.ServiceReference2.toBigSortResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class toBigSortResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string toBigSortResult;
        
        public toBigSortResponseBody() {
        }
        
        public toBigSortResponseBody(string toBigSortResult) {
            this.toBigSortResult = toBigSortResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class toSmallSortRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="toSmallSort", Namespace="http://tempuri.org/", Order=0)]
        public WSTEST1.ServiceReference2.toSmallSortRequestBody Body;
        
        public toSmallSortRequest() {
        }
        
        public toSmallSortRequest(WSTEST1.ServiceReference2.toSmallSortRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class toSmallSortRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string str;
        
        public toSmallSortRequestBody() {
        }
        
        public toSmallSortRequestBody(string str) {
            this.str = str;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class toSmallSortResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="toSmallSortResponse", Namespace="http://tempuri.org/", Order=0)]
        public WSTEST1.ServiceReference2.toSmallSortResponseBody Body;
        
        public toSmallSortResponse() {
        }
        
        public toSmallSortResponse(WSTEST1.ServiceReference2.toSmallSortResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class toSmallSortResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string toSmallSortResult;
        
        public toSmallSortResponseBody() {
        }
        
        public toSmallSortResponseBody(string toSmallSortResult) {
            this.toSmallSortResult = toSmallSortResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface WebServiceTestSoapChannel : WSTEST1.ServiceReference2.WebServiceTestSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class WebServiceTestSoapClient : System.ServiceModel.ClientBase<WSTEST1.ServiceReference2.WebServiceTestSoap>, WSTEST1.ServiceReference2.WebServiceTestSoap {
        
        public WebServiceTestSoapClient() {
        }
        
        public WebServiceTestSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public WebServiceTestSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public WebServiceTestSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public WebServiceTestSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        WSTEST1.ServiceReference2.HelloWorldResponse WSTEST1.ServiceReference2.WebServiceTestSoap.HelloWorld(WSTEST1.ServiceReference2.HelloWorldRequest request) {
            return base.Channel.HelloWorld(request);
        }
        
        public string HelloWorld() {
            WSTEST1.ServiceReference2.HelloWorldRequest inValue = new WSTEST1.ServiceReference2.HelloWorldRequest();
            inValue.Body = new WSTEST1.ServiceReference2.HelloWorldRequestBody();
            WSTEST1.ServiceReference2.HelloWorldResponse retVal = ((WSTEST1.ServiceReference2.WebServiceTestSoap)(this)).HelloWorld(inValue);
            return retVal.Body.HelloWorldResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<WSTEST1.ServiceReference2.HelloWorldResponse> WSTEST1.ServiceReference2.WebServiceTestSoap.HelloWorldAsync(WSTEST1.ServiceReference2.HelloWorldRequest request) {
            return base.Channel.HelloWorldAsync(request);
        }
        
        public System.Threading.Tasks.Task<WSTEST1.ServiceReference2.HelloWorldResponse> HelloWorldAsync() {
            WSTEST1.ServiceReference2.HelloWorldRequest inValue = new WSTEST1.ServiceReference2.HelloWorldRequest();
            inValue.Body = new WSTEST1.ServiceReference2.HelloWorldRequestBody();
            return ((WSTEST1.ServiceReference2.WebServiceTestSoap)(this)).HelloWorldAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        WSTEST1.ServiceReference2.toBigSortResponse WSTEST1.ServiceReference2.WebServiceTestSoap.toBigSort(WSTEST1.ServiceReference2.toBigSortRequest request) {
            return base.Channel.toBigSort(request);
        }
        
        public string toBigSort(string str) {
            WSTEST1.ServiceReference2.toBigSortRequest inValue = new WSTEST1.ServiceReference2.toBigSortRequest();
            inValue.Body = new WSTEST1.ServiceReference2.toBigSortRequestBody();
            inValue.Body.str = str;
            WSTEST1.ServiceReference2.toBigSortResponse retVal = ((WSTEST1.ServiceReference2.WebServiceTestSoap)(this)).toBigSort(inValue);
            return retVal.Body.toBigSortResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<WSTEST1.ServiceReference2.toBigSortResponse> WSTEST1.ServiceReference2.WebServiceTestSoap.toBigSortAsync(WSTEST1.ServiceReference2.toBigSortRequest request) {
            return base.Channel.toBigSortAsync(request);
        }
        
        public System.Threading.Tasks.Task<WSTEST1.ServiceReference2.toBigSortResponse> toBigSortAsync(string str) {
            WSTEST1.ServiceReference2.toBigSortRequest inValue = new WSTEST1.ServiceReference2.toBigSortRequest();
            inValue.Body = new WSTEST1.ServiceReference2.toBigSortRequestBody();
            inValue.Body.str = str;
            return ((WSTEST1.ServiceReference2.WebServiceTestSoap)(this)).toBigSortAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        WSTEST1.ServiceReference2.toSmallSortResponse WSTEST1.ServiceReference2.WebServiceTestSoap.toSmallSort(WSTEST1.ServiceReference2.toSmallSortRequest request) {
            return base.Channel.toSmallSort(request);
        }
        
        public string toSmallSort(string str) {
            WSTEST1.ServiceReference2.toSmallSortRequest inValue = new WSTEST1.ServiceReference2.toSmallSortRequest();
            inValue.Body = new WSTEST1.ServiceReference2.toSmallSortRequestBody();
            inValue.Body.str = str;
            WSTEST1.ServiceReference2.toSmallSortResponse retVal = ((WSTEST1.ServiceReference2.WebServiceTestSoap)(this)).toSmallSort(inValue);
            return retVal.Body.toSmallSortResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<WSTEST1.ServiceReference2.toSmallSortResponse> WSTEST1.ServiceReference2.WebServiceTestSoap.toSmallSortAsync(WSTEST1.ServiceReference2.toSmallSortRequest request) {
            return base.Channel.toSmallSortAsync(request);
        }
        
        public System.Threading.Tasks.Task<WSTEST1.ServiceReference2.toSmallSortResponse> toSmallSortAsync(string str) {
            WSTEST1.ServiceReference2.toSmallSortRequest inValue = new WSTEST1.ServiceReference2.toSmallSortRequest();
            inValue.Body = new WSTEST1.ServiceReference2.toSmallSortRequestBody();
            inValue.Body.str = str;
            return ((WSTEST1.ServiceReference2.WebServiceTestSoap)(this)).toSmallSortAsync(inValue);
        }
    }
}
